name: Run Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright
        run: python -m playwright install --with-deps

      - name: Run Pytest
        run: pytest --clean-alluredir --alluredir=allure-results

      - name: Generate Allure report
        uses: andgineer/allure-report@v3.6
        if: always()
        with:
          allure-results: allure-results
          report-dir: allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
